name: "Lampac"
description: "My first real add-on!"
version: "1.0.0"
slug: "lampac_hass"
advanced: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
hassio_role: manager  
ingress: true
ingress_port: 9118
host_network: true
#ingress_entry: /admin/auth
webui: "http://[HOST]:[PORT:9118]/admin/auth"
init: true  
  
  
startup: before
ports:
  9118/tcp: 9118
  #21/tcp: 21
  #8000/tcp: 8000  
